
services:
  rag-ui-service:
    container_name: "rag-ui-service"
    #image: rag-ui-local:latest
    image: mnpma/multimodal-rag-ui:1.0
    ports:
      - "7000:80"

  pgvector-service:
    image: ankane/pgvector
    container_name: pgvector-service
    environment:
      POSTGRES_DB: embd
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgvector-db:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d

  rag-api-service:
    container_name: "rag-api-service"
    #image: rag-api-local:latest
    image: mnpma/multimodal-rag-api:1.0
    environment:
      OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
      OPEN_AI_ENDPOINT: ${OPEN_AI_ENDPOINT}
      OPEN_AI_COMPLETIONS_PATH: ${OPEN_AI_COMPLETIONS_PATH}
      CHAT_MODEL: ${CHAT_MODEL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGVECTOR_URL: ${PGVECTOR_URL}
      MISTRAL_AI_API_KEY: ${MISTRAL_AI_API_KEY}
      IMAGE_MODEL: ${IMAGE_MODEL}
      IMAGE_AI_COMPLETIONS_PATH: ${IMAGE_AI_COMPLETIONS_PATH}
    ports:
      - 8081:8081
    depends_on:
      - pgvector-service
